n_dim1: 8 #fixed
n_dim2: 3 #fixed

country: Hungary  # the country canme selected among the following: Zimbabwe - Peru - Vietnam - Hungary

#d2
dist_Pd2 : [0.35, 0.45, 0.20]

mixing_type: 'assortative_mixing' #random_mixing or assortative_mixing
r  : [0.60, 0.5, 0.65]  
ds : [0.6, 0.6, 0.5]
activity: [0.2, 0.4, 0.4]
