# params epidemic
N_iter: 5 # number of iterations
seed: 100 # nomber of initial infected individuals
mu_val: 0.25 # recovery rate
eps_val: 0.4 # incubation rate
stop: 200 # number of time step to run 
r0: 2.7 # basic reproductive number


