n_dim1: 8
n_dim2: 3
n_dim3: 3

country: Hungary

#d2
dist_Pd2 : [0.35, 0.45, 0.20]

mixing_type: 'assortative_mixing' #random_mixing or assortative_mixing
r  : [0.60, 0.5, 0.65] 
ds : [0.6, 0.6, 0.5]
activity: [0.2, 0.4, 0.4]

#d3
dist_Pd3 : [0.3, 0.3, 0.4]
mixing_type_d3: 'assortative_mixing' #random_mixing or assortative_mixing